version: "3.4"

x-env-variables: &common-variables
    INFLUXDB_DB: test
    INFLUXDB_ADMIN_USER: root
    INFLUXDB_ADMIN_PASSWORD: password
    INFLUXDB_HTTP_AUTH_ENABLED: "true"
    TZ: Asia/Taipei
    
services: 
    database: 

        image: influxdb:1.8.10
        volumes: 
            - "db_data:/var/lib/influxdb"
        restart: always
        ports:
            - "8086:8086"
            - "8083:8083"
        environment: *common-variables
    
    grafana:
        image: grafana/grafana-oss
        restart: unless-stopped
        ports:
            - 3000:3000
          
        
volumes:
    db_data: